import { createFileRoute, Link } from "@tanstack/react-router";
import { BarChart3, Boxes, ClipboardList, Package, ShoppingBag, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { formatRWF } from "@/data/products";
import { getOrders, type Order } from "@/lib/orders";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Admin Dashboard — Net Phantom Store" }] }), component: AdminPage });

function AdminPage() {
  const [orders, setOrders] = useState<Order[]>([]);
  useEffect(() => setOrders(getOrders()), []);
  const revenue = orders.filter(o => o.paymentStatus === "paid").reduce((s, o) => s + o.total, 0);
  const pending = orders.filter(o => o.status === "pending" || o.status === "processing").length;
  const units = orders.reduce((s, o) => s + o.items.reduce((n, i) => n + i.qty, 0), 0);
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[0.3em] text-primary">Control center</div><h1 className="mt-2 font-display text-3xl font-black sm:text-4xl">Store Dashboard</h1></div><Link to="/" className="text-sm text-muted-foreground hover:text-primary">View store</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Revenue",formatRWF(revenue),BarChart3],["Orders",String(orders.length),ClipboardList],["Pending",String(pending),ShoppingBag],["Units sold",String(units),Boxes]].map(([label,value,Icon]) => <div key={String(label)} className="card-glow rounded-xl p-5"><Icon className="h-5 w-5 text-primary" /><div className="mt-4 text-xs font-bold uppercase tracking-widest text-muted-foreground">{label}</div><div className="mt-1 font-display text-2xl font-black">{value}</div></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_300px]"><section className="card-glow rounded-xl p-6"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold">Recent orders</h2><span className="text-xs text-muted-foreground">{orders.length} total</span></div>{orders.length === 0 ? <p className="mt-8 text-sm text-muted-foreground">No orders yet. Orders created through checkout will appear here on this device.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="py-3 pr-4">Order</th><th className="py-3 pr-4">Customer</th><th className="py-3 pr-4">Total</th><th className="py-3">Status</th></tr></thead><tbody>{orders.slice(0,10).map(o => <tr key={o.id} className="border-b border-border/50"><td className="py-3 pr-4 font-semibold">{o.id}</td><td className="py-3 pr-4">{o.customer.name}</td><td className="py-3 pr-4">{formatRWF(o.total)}</td><td className="py-3 capitalize">{o.status}</td></tr>)}</tbody></table></div>}</section><aside className="card-glow rounded-xl p-6"><h2 className="font-display text-lg font-bold">Admin modules</h2><div className="mt-4 space-y-3 text-sm"><div className="flex items-center gap-3"><Package className="h-4 w-4 text-primary" /> Products & inventory</div><div className="flex items-center gap-3"><ClipboardList className="h-4 w-4 text-primary" /> Orders & fulfillment</div><div className="flex items-center gap-3"><Users className="h-4 w-4 text-primary" /> Customers</div><div className="flex items-center gap-3"><BarChart3 className="h-4 w-4 text-primary" /> Sales reports</div></div><p className="mt-6 text-xs text-muted-foreground">This first dashboard is local-only. Before launch, connect it to authenticated server/database storage so customers cannot access admin data.</p></aside></div></div>;
}
